name = "metingapi"
main = "./src/worker.js"
compatibility_date = "2024-09-23"

compatibility_flags = ["nodejs_compat"]

[vars]
HTTP_PREFIX = ""
METING_URL = "https://api.vedaru.cn/"
METING_TOKEN = "token"
METING_COOKIE_ALLOW_HOSTS = "https://api.vedaru.cn/"

compatibility_flags = ["nodejs_compat"]