name = "meting-api"
main = "./src/worker.js"
compatibility_date = "2024-01-01"

compatibility_flags = ["nodejs_compat"]

[vars]
HTTP_PREFIX = ""
METING_URL = ""
METING_TOKEN = "token"
METING_COOKIE_ALLOW_HOSTS = ""

compatibility_flags = ["nodejs_compat"]